### ISSUE TITLE
update CI pipeline to have publish and test be two jobs in the same workflow

### ISSUE THREAD

**Issue by fastfrwrd** [spotify/web-scripts#525]
The current CI pipeline has a good bit of duplication in running tests, where it could and should look like:

```yaml
name: Review and Deploy
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# Environment variables available to all jobs and steps in this workflow
env:
  # ...
jobs:
  test:
    name: Lint and Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 10.x, 12.x, 14.x ]
    steps:
    # ...
  deploy:
    name: Setup, Build, Publish, and Deploy
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/master'
    steps:
    # ...
```
